services:
  - type: web
    name: Carambar-co
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/app.js
    envVars:
      - key: NODE_VERSION
        value: 20.12.2
